services:
  web:
    build: .
    env_file:
      - shared.env
    volumes:
      - .:/app 
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    env_file:
      - shared.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:

