name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r django_appstore_project/requirements.txt

      - name: Run Django Tests
        run: |
          python manage.py test

  lint:
    runs-on: ubuntu-latest
    name: Lint Check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install lint tools
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black

      - name: Run Flake8 Lint
        run: |
          flake8 --config=django_appstore_project/.flake8 .

      - name: Check Code Formatting with Black
        run: |
          black --config django_appstore_project/pyproject.toml --check .
